version: "2"

services:
    nginx:
        image: nginx:1.17
        working_dir: /app
        volumes:
            - ./:/app
            - ./docker/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8888:80

    php:
        build:
            context: ./
            dockerfile: ./docker/php-fpm/Dockerfile
        working_dir: /app
        volumes:
            - ./:/app
            - ~/.ssh:/root/.ssh

    db:
        image: mysql:5.7
        command: mysqld --user=root --skip-sync-frm --innodb_flush_log_at_trx_commit=0 --innodb-support-xa=0 --bind-address=0.0.0.0 --query-cache-type=1
        ports:
            - 3317:3306
        volumes:
            - ./docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}

    db_test:
        image: mysql:5.7
        command: mysqld --user=root --skip-sync-frm --innodb_flush_log_at_trx_commit=0 --innodb-support-xa=0 --bind-address=0.0.0.0 --query-cache-type=1
        ports:
            - 3318:3306
        volumes:
            - ./docker/data/db_test:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_TEST_PASSWORD}
            MYSQL_DATABASE: ${DB_TEST_DATABASE}
            MYSQL_USER: ${DB_TEST_USERNAME}
            MYSQL_PASSWORD: ${DB_TEST_PASSWORD}
